#!/usr/bin/env python3
"""Compute optional FID/KID for paired SD3 edit sets.

Requires torchmetrics. If unavailable, the script exits with a clear message.
It searches clean/adv paired SDEdit outputs generated by diff_mist_SD3_v2.py.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import torch
from PIL import Image
import torchvision.transforms as T


def _collect_pairs(root: Path):
    pairs = []
    for clean in root.rglob("*_sdedit_clean_noise_*.png"):
        adv = Path(str(clean).replace("_sdedit_clean_noise_", "_sdedit_adv_noise_"))
        if adv.exists():
            m = re.search(r"_sdedit_clean_noise_([0-9.]+)\.png$", clean.name)
            sigma = m.group(1) if m else "unknown"
            pairs.append((sigma, clean, adv))
    return pairs


def _img_tensor(path: Path) -> torch.Tensor:
    img = Image.open(path).convert("RGB")
    return T.ToTensor()(img).mul(255).to(torch.uint8)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default="out_sd3")
    parser.add_argument("--out", default="out_sd3/fid_kid.json")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--kid", action="store_true")
    args = parser.parse_args()

    try:
        from torchmetrics.image.fid import FrechetInceptionDistance
        from torchmetrics.image.kid import KernelInceptionDistance
    except Exception as exc:
        raise SystemExit(f"torchmetrics image metrics unavailable: {exc}")

    pairs = _collect_pairs(Path(args.root))
    if not pairs:
        raise SystemExit("no paired clean/adv SDEdit images found")

    by_sigma = {}
    for sigma, clean, adv in pairs:
        by_sigma.setdefault(sigma, []).append((clean, adv))

    device = torch.device(args.device if args.device != "cuda" or torch.cuda.is_available() else "cpu")
    results = {}
    for sigma, items in sorted(by_sigma.items()):
        fid = FrechetInceptionDistance(feature=2048, normalize=False).to(device)
        kid = KernelInceptionDistance(subset_size=min(50, len(items)), normalize=False).to(device) if args.kid else None
        for clean, adv in items:
            c = _img_tensor(clean).unsqueeze(0).to(device)
            a = _img_tensor(adv).unsqueeze(0).to(device)
            fid.update(c, real=True)
            fid.update(a, real=False)
            if kid is not None:
                kid.update(c, real=True)
                kid.update(a, real=False)
        row = {"count": len(items), "fid": float(fid.compute().detach().cpu().item())}
        if kid is not None:
            km, ks = kid.compute()
            row["kid_mean"] = float(km.detach().cpu().item())
            row["kid_std"] = float(ks.detach().cpu().item())
        results[sigma] = row

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"root": args.root, "results": results}, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps({"out": str(out), "results": results}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
